---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  sudo: true
  remote_user: vagrant

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: apps
  sudo: true
  remote_user: vagrant

  roles:
    - app

- name: configure nginx reverse proxy
  hosts: nginx
  sudo: true
  remote_user: vagrant

  roles:
    - nginx

- name: deploy MySQL and configure the databases
  hosts: db
  sudo: true
  remote_user: vagrant

  roles:
    - mysql

- name: Setup cache (memcached)
  hosts: cache
  sudo: true
  remote_user: vagrant

  tasks:
    - name: Install memcached
      apt: name=memcached state=present

    - name: Update the memcached config
      action: copy src=config/memcached.conf dest=/etc/memcached.conf
      notify: Restart memcached

  handlers:
    - name: Restart memcached
      action: service name=memcached state=restarted

- name: Run migrations
  hosts: db_opt
  sudo: true
  remote_user: vagrant

  tasks:
    - name: Migrate database
      shell: "{{ app_virtualenv_path }}/bin/python {{ app_path }}/manage.py syncdb --noinput"
      # shell: "{{ app_virtualenv_path }}/bin/python {{ app_path }}/manage.py migrate --noinput"
      check_mode: no
