- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Install MySQL packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb
  when: mysql_installed.stat.exists == false

- name: Delete innodb log files created by apt package after initial install.
  file: path={{ mysql_datadir }}/{{item}} state=absent
  with_items:
    - "ib_logfile0"
    - "ib_logfile1"
  when: mysql_installed.stat.exists == false

- name: Update MySQL root password for all root accounts
  sudo: yes
  mysql_user:
    name: "{{ database_root_user }}"
    password: "{{ database_root_pass }}"
    host_all: yes
  when: mysql_installed.stat.exists == false

- name: Copy .my.cnf file with root password credentials.
  template:
    src: dot_my.cnf
    dest: "{{ mysql_user_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: create mysql database
  mysql_db: name={{ database_name }} state=present

- name: Create MySQL user
  sudo: yes
  mysql_user:
    name: "{{ database_user }}"
    host: "{{ item }}"
    password: "{{ database_pass }}"
    check_implicit_admin: yes
    priv: "{{ database_name }}.*:ALL,GRANT"
  with_items: groups.apps

- name: Ensure MySQL to running and started on boot up
  service: name=mysql state=started enabled=yes

- name: Remove MySQL test database
  mysql_db: "name='test' state=absent"

- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Get list of hosts for the anonymous user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false
  always_run: true

- name: Remove anonymous MySQL users.
  mysql_user:
     name: ""
     host: "{{ item }}"
     state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines|default([]) }}"
