---
- name: Create the virtualenv
  command: virtualenv {{ app_virtualenv_path }} --no-site-packages
    creates={{ app_virtualenv_path }}/bin/activate

- name: Install uwsgi in virtualenv
  pip: virtualenv={{ app_virtualenv_path }} name=uwsgi
  tags: packages

- name: Install python-mysqldb in virtualenv
  pip: virtualenv={{ app_virtualenv_path }} name=mysqlclient
  tags: packages

- name: Copy uwsgi config
  template: src=uwsgi.yaml
    dest={{ app_user_home_dir }}/uwsgi.yaml
    owner={{ app_user }}
    group={{ app_group }}
